apiVersion: apps/v1
kind: Deployment

metadata:
  name: webapp

spec:
  replicas: 3
  selector:
    matchlabels:
      app: label-value

  template:
    metadata:
      name: webapp-pod
      labels:
        app: label-value
    spec:
      containers:
        - image: hossamramadan/webapp
          name: webapp-container
          imagePollPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "100Mi"