apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: wepapp-pod

  ports:
    - port: 8080
      targetport: 80  
      nodeport: 30005